from tkinter import *
def disable():
        resultBox.configure(state="disable")
#end of disable()
def addbtn(eventSpec):
    resultBox.configure(state="normal")
    operand1 = firstBox.get(1.0,END)
    operand2 = secondBox.get(1.0,END)
    result = int(operand1)+int(operand2)
    resultBox.insert(1.0,result)
    if(resultBox):
        disable()
#end of addbtn()
def subbtn(eventSpec):
    resultBox.configure(state="normal")
    operand1 = firstBox.get(1.0,END)
    operand2 = secondBox.get(1.0,END)
    result = int(operand1)-int(operand2)
    resultBox.insert(1.0,result)
    if(resultBox):
        disable()
#end of subbtn()
def mulbtn(eventSpec):
    resultBox.configure(state="normal")
    operand1 = firstBox.get(1.0,END)
    operand2 = secondBox.get(1.0,END)
    result = int(operand1)*int(operand2)
    resultBox.insert(1.0,result)
    if(resultBox):
        disable()
#end of mulbtn()
def divbtn(eventSpec):
    resultBox.configure(state="normal")
    operand1 = firstBox.get(1.0,END)
    operand2 = secondBox.get(1.0,END)
    result = int(operand1)/int(operand2)
    resultBox.insert(1.0,result)
    if(resultBox):
        disable()
#end of divbtn()
def modbtn(eventSpec):
    resultBox.configure(state="normal")
    operand1 = firstBox.get(1.0,END)
    operand2 = secondBox.get(1.0,END)
    result = int(operand1)%int(operand2)
    resultBox.insert(1.0,result)
    if(resultBox):
        disable()
#end of modbtn()
def clearbtn(eventSpec):
    resultBox.configure(state="normal")
    firstBox.delete(1.0,END)
    secondBox.delete(1.0,END)
    resultBox.delete(1.0,END)
#end of clearbtn()
#MAIN BLOCK OF CODE 
mainContainer = Tk()
mainContainer.geometry("500x700")
mainContainer.title("Sample GUI Calculator")
firstLbl = Label(mainContainer,height=1,width=10,text="Operand 1 : ")
secondLbl = Label(mainContainer,height=1,width=10,text="Operand 2 : ")
resultLbl = Label(mainContainer,height=1,width=10,text="Result : ")
firstBox = Text(mainContainer,height=1,width=20,bg="pink",bd=3)
secondBox = Text(mainContainer,height=1,width=20,bg="pink",bd=3)
resultBox = Text(mainContainer,height=1,width=20,bg="pink",bd=3)
resultBox.configure(state="disabled")
addBtn = Button(mainContainer,text="Addition",height=2,width=20,bg="brown",fg="white")
subBtn = Button(mainContainer,text="Substraction",height=2,width=20,bg="brown",fg="white")
mulBtn = Button(mainContainer,text="Multiplication",height=2,width=20,bg="brown",fg="white")
divBtn = Button(mainContainer,text="division",height=2,width=20,bg="brown",fg="white")
modBtn = Button(mainContainer,text="modules",height=2,width=20,bg="brown",fg="white")
modBtn = Button(mainContainer,text="modules",height=2,width=20,bg="brown",fg="white")
clear = Button(mainContainer,text="Clear",height=2,width=20,bg="brown",fg="white")
firstLbl.grid(row=1,column=4)
firstBox.grid(row=1,column=5)
secondLbl.grid(row=2,column=4)
secondBox.grid(row=2,column=5)
resultLbl.grid(row=3,column=4)
resultBox.grid(row=3,column=5)
addBtn.grid(row=4,column=2,padx=5)
subBtn.grid(row=4,column=3,padx=5)
mulBtn.grid(row=4,column=4,padx=5)
divBtn.grid(row=4,column=5,padx=5)
modBtn.grid(row=4,column=6,padx=5)  
clear.grid(row=4,column=7,padx=5)
addBtn.bind("<Button-1>",addbtn)
subBtn.bind("<Button-1>",subbtn)
mulBtn.bind("<Button-1>",mulbtn)
divBtn.bind("<Button-1>",divbtn)
modBtn.bind("<Button-1>",modbtn)
clear.bind("<Button-1>",clearbtn)
mainContainer.mainloop()
#end of code